name: ai_barcode_scanner
description: A universal AI barcode and QR code scanner for Flutter based on MLKit. Uses CameraX on Android, AVFoundation on iOS and Apple Vision & AVFoundation on macOS.
version: 3.4.1
homepage: https://mohesu.com
repository: https://github.com/mohesu/barcode_scanner.git
issue_tracker: https://github.com/mohesu/barcode_scanner/issues
screenshots:
  - description: 'Barcode Scanner'
    path: assets/final.PNG

topics:
  - qr-code
  - barcode
  - scanner
  - camera
  - mobile-scanner

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
